services:
  postgres:
    container_name: nest-rocketseat
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-rocketseat
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
